import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
// import Link from 'next/link';

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Evelyn portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <section id='hero' className='snap-start'> 
        {/* has snap center due to parent has snap attribute */}
         <Hero />
        </section>
        <section id='about' className='snap-center'>
          <About />
        </section>
    <section id='experience' className='snap-center'>
      <Experience />
    </section>
    <section id='skills' className='snap-start'>
      <Skills />
    </section>
    <section id='projects' className='snap-start'>
      <Projects />
    </section>
    <section id='contact-me' className='snap-start'>
      <ContactMe />
    </section>
{/* <Link href="#hero">
<footer className="sticky bottom-5 w-full cursor-pointer">
  <div className="flex items-center justify-center">
    <img className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer" src="https://cdn.iconscout.com/icon/premium/png-256-thumb/scroll-top-4107740-3399596.png" alt="" /></div></footer></Link> */}

    </div>
  )
}
