import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import ContactMe from "../components/Contact/ContactMe";
import WorkExperience from "../components/Experience/WorkExperience";
import Header from "../components/Header";
import Hero from "../components/Hero/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skill/Skills";
import Link from "next/link";
import { GetStaticProps } from "next";
import { Experience, PageInfo, Project, Skill, Social } from "../typings";
import { fetchPageInfos } from "../utils/fetchPageInfo";
import { fetchExperiences } from "../utils/fetchExperiences";
import { fetchSkills } from "../utils/fetchSkills";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSocials } from "../utils/fetchSocials";


type Props = {
  pageInfo: PageInfo[];
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
}

const Home=({pageInfo,experiences,skills,projects,socials}:Props)=> {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Evelyn portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header socials={socials}/>
      <section id="hero" className="snap-start">
        {/* has snap center due to parent has snap attribute */}
        <Hero pageInfo={pageInfo} />
      </section>
      <section id="about" className="snap-center">
        <About pageInfo={pageInfo}/>
      </section>
      <section id="experience" className="snap-center">
        <WorkExperience experiences={experiences}/>
      </section>
      <section id="skills" className="snap-start">
        <Skills skills={skills}/>
      </section>
      <section id="projects" className="snap-start">
        <Projects projects={projects}/>
      </section>
      <section id="contact" className="snap-start">
        <ContactMe pageInfo={pageInfo}/>
      </section>
      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <img
              className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
              src="https://i.pinimg.com/474x/59/6d/2b/596d2b56556c048a191abb070b3d6472.jpg"
              alt="go-back"
            />
          </div>
        </footer>
      </Link>
    </div>
  );
}
export default Home;

export const getStaticProps:GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo[] = await fetchPageInfos();
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocials();
  return{
    props:{
      pageInfo,
      experiences,
      skills,
      projects,
      socials,
    },
    revalidate:30,
  };
}
